<?php 
		unset($_SESSION["trans_demond_add_email"]);
        unset($_SESSION["trans_demond_add_title"]);
        unset($_SESSION["trans_demond_add_country"]);
        unset($_SESSION["trans_demond_add_state"]);
        unset($_SESSION["trans_demond_add_city"]);
        unset($_SESSION["trans_demond_add_countryback"]);
        unset($_SESSION["trans_demond_add_stateback"]);
        unset($_SESSION["trans_demond_add_cityback"]);
        unset($_SESSION["trans_demond_add_catergory"]);
        unset($_SESSION["trans_demond_add_contactpub"]);
        unset($_SESSION["trans_demond_add_emailshow"]);
		unset($_SESSION["trans_demond_add_postdescription"]);
?>