 <?php 		
        unset($_SESSION["demond_add_email"]);
        unset($_SESSION["demond_add_title"]);
        unset($_SESSION["demond_add_country"]);
        unset($_SESSION["demond_add_state"]);
        unset($_SESSION["demond_add_city"]);
        unset($_SESSION["demond_add_catergory"]);
        unset($_SESSION["demond_add_contactpub"]);
        unset($_SESSION["demond_add_emailshow"]);
        unset($_SESSION["demond_add_postdescription"]);
  ?>