<?php 
	    unset($_SESSION["supply_add_email"]);
        unset($_SESSION["supply_add_title"]);
        unset($_SESSION["supply_add_country"]);
        unset($_SESSION["supply_add_state"]);
        unset($_SESSION["supply_add_city"]);
        unset($_SESSION["supply_add_countryback"]);
        unset($_SESSION["supply_add_stateback"]);
        unset($_SESSION["supply_add_cityback"]);
        unset($_SESSION["supply_add_catergory"]);
        unset($_SESSION["supply_add_contactpub"]);
        unset($_SESSION["supply_add_emailshow"]);
		unset($_SESSION["supply_add_postdescription"]);
		unset($_SESSION["supply_add_backdate"]);
?>